### ISSUE TITLE
Hi skarone. Can i have some guide to setup PipeL 

### ISSUE THREAD

**Issue by tws0002** [skarone/PipeL#1]
Hi skarone. Can i have some guide to setup PipeL? 

Thanks 
Desmond

**Comment by skarone** [comment]
Hey! sorry I was very busy.
If you have to install it for maya... You have to do 2 things, one is add the path where you downloaded Pipel to the PYTHONPATH, and then inside the install folder there is a userSetup.mel that you have to copy to your maya/scripts folder.

**Comment by tws0002** [comment]
Hey thanks for the reply!! Thanks for the sharing. i find a way to launch the pipel with nuke, maya and houdini. is this the final version or still in develop?

but I can't found the plugin u list in the document!! 'Alembic To Arnold Plugin!'. can u share this? 

Thanks 
Desmond
